server:
  port: 8084

spring:
  application:
    name: cart-service

  data:
    redis:
      host: 16.16.121.11
      port: 6379
      password: Yogesh@#12   # uncomment if your local Redis requires auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
