server:
  port: 8085

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://ep-late-base-az4ls7i9-pooler.c-3.ap-southeast-1.aws.neon.tech/orderservicedb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_WbFiBN4Q2hJK
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# MUST match product-service's internal.api-key — used for the
# decrement-stock / restore-stock calls during checkout and cancellation.
internal:
  api-key: Internal5J0twCinb5TLXqsegv52zp6v5NyoXKTJ1WDna74yR7UxYqXQNS6OGlH4m1dpCLAO1KuclXxgnhaZ7NcEmTHDBURtMFazSwHHkD0gbc8fwAALUp5c3GfvB2f1hbMY5Sor

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
