server:
  port: 8083

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://ep-late-base-az4ls7i9-pooler.c-3.ap-southeast-1.aws.neon.tech/productservicedb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_WbFiBN4Q2hJK
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

services:
  user-service:
    url: http://user-service

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

internal:
  api-key: ${INTERNAL_API_KEY:change-this-internal-shared-secret}
